### ISSUE TITLE
about the setting z-score

### ISSUE THREAD

**Issue by LeoStrange26** [THU-BPM/Robust_Watermark#5]
Could you tell what is the threshold of z-score set?
(In order to reproduce the results in the paper.)

**Comment by exlaw** [comment]
The experiments in the article did not use a fixed z-threshold setting. Instead, we calculated all the z-scores for the human text and the watermarked text, sorted all the z-scores, and then compared using the settings where the false positive rate (FPR) was 1%, 5%, and the optimal F1 score (considering that different methods may have z-score settings that introduce unfair factors, this approach provides a more fair comparison).

**Comment by LeoStrange26** [comment]
It is known to all that FPR is equivalent to p-value, and p-value is strongly related to z-score. Are the variances and means used in the z-score calculation the actual statistics used, or the expected value (i.e., 0) in the training?

**Comment by LeoStrange26** [comment]
or to say, for instance , what is the z-score of 1% FPR relative to the scheme in your article? (cause in your paper it seems like the z-score is divided by N,  but typical z-score seems to be divided by N^0.5, which make me a little confused)

**Comment by exlaw** [comment]
Sorry for the slightly late reply. First, it needs to be clarified that there is no necessary connection between p-value and FPR, whether using the p-value from methods like Exp-edit or using the the z-score in KGW or SIR does not affect our F1 calculation, even the specific calculation formula does not affect it. Because our evaluation method is as follows: assuming we have N watermarked texts and N human texts, we first generate a z-score or p-value  for each text, and then we search for a threshold to see the classification effect. At this time, the selection of the threshold may cause the problem of unfair comparison of different methods. We have drawn the PR curve and found the F1 value when the FPR is 10% on the PR curve, which completely avoids the unfairness caused by different methods due to different threshold selections.
